language: node_js

service:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

node_js:
- 'stable'

env:
  global:
    - DATABASE_TEST_URL="postgres://postgres:password@127.0.0.1:5432/travis_ci_test"
    - SECRET="secret"

install: npm install

dist: trusty

cache:
  directories:
    - "node_modules"

after_success: npm run coverage
