version: "3"
services:
  magma-backend: 
    image: davidteejay/magma-backend
    ports: 
      - 5000:5000
    command: npm run dev
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
  db:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    